POST http://localhost:3000/signin
Content-Type: application/json

{

    "email":"111@mail.com",
    "password":"111Qq2"
}

# GET http://localhost:3000/get-upload-url

# POST http://localhost:3000/create-blog 
# Content-Type: application/json
# {
#     "blog-name":"hey"
# }


# POST http://localhost:3000/create-blog 
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1N2YxMzZjMWRhZDM0MGJkOWU0MDA3ZCIsImlhdCI6MTcwMjgyNjg2MH0.5VoqPsow7ykA0WCor-PpZwEVtJBkO1tLjKkmSadujpg

# {
#     "title":"test huiwa @ 2 h2ih # &% &&* 2",
#     "banner":"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0f/ba/29/5c/img-worlds-of-adventure.jpg?w=1800&h=-1&s=1",
#     "description":"hhhhh",
#     "content":{
#         "blocks":[1,2]
#     },
#     "tags":["11","222"]
# # }

# GET http://localhost:3000/latest-blogs

# GET http://localhost:3000/trending-blogs

# POST http://localhost:3000/search-blogs
# Content-Type: application/json

# {
#   "tag": "life",
#   "limit":2,
#   "eliminate_blog":"Biological-Clock5CU5mySgohLv7p6km7Ppv"

# }

# POST http://localhost:3000/search-users
# Content-Type: application/json

# {
#   "query": "1"
# }

# POST http://localhost:3000/get-blog
# Content-Type: application/json

# {
#   "blog_id": "Solar-Adventure-The-Start-of-A-New-ChapterwmG90HqmpVZlxi8KO5LUr"
# }

# POST http://localhost:3000/get-profile
# Content-Type: application/json

# {
#   "username": "TheOne"
# }

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1N2YzZDFlM2ZmYjdkNjA2YjBlYTI1MSIsImlhdCI6MTcwMzc4MDE1MH0.kS8oNoOx5m3cSTRwJMsr-iiBnAYLmsTqC6MQWmE7-WQ

# POST http://localhost:3000/change-password
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OGZlZGViNmI4OTA5ZGE1MzJjOGExOSIsImlhdCI6MTcwMzk0NDc1NX0.QoAd2A9CJt4P2ZyXUm4ZOQFZ91ZwiolwJXute-hSjsw

# {
#     "CurrentPassword":"111Qq1",
#     "NewPassword":"111Qq2"
#  }
